---
name: Yak Build
on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.gh*'

jobs:
  build:  
    strategy:
      matrix:
        os: [macos-latest, windows-latest] #, ubuntu-latest] # Not supported yet
    runs-on: ${{ matrix.os }}

    steps:
    - run: echo ${{matrix.os}}

    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "6.0.x"

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.x"

    - run: dotnet build Crash.sln

    - name: Install Powershell
      run: |
        dotnet tool install --global PowerShell

    - name: Build Yak Package
      run: |
        .\Scripts\YakCompile.ps1 -Path $in -DestinationPath $out -Config Release -os ${{ matrix.os }}
      shell: powershell

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: Crash\bin\Release\net48\*.yak
